#!/bin/bash

usage() {
  echo "Usage: ${0} -m MESSAGE [-p]";
  echo "  -m MeSSAGE The commit message";
  echo "  -p If specified will push changes to remote branch";
  exit 1;
}

while getopts "m:p" OPT;
do
  case ${OPT} in
    p) PUSH="git push" ;;
    m) MESSAGE="${OPTARG}" ;;
    ?) usage ;;
  esac
done

if [[ -z "$MESSAGE" ]] || [[ "${MESSAGE}" = '' ]] || [[ "${MESSAGE}" = -* ]]
then 
  echo "You must provide a message"; 
  usage; 
fi

echo "heloo";

git add . &>/dev/null

if [[ "${?}" -ne 0 ]]
then 
  echo "Could not stage files" >&2
  exit 1;
fi

echo "Staged all files.";

git commit -m "$MESSAGE" &>/dev/null

if [[ "${?}" -ne 0 ]]
then 
  echo "Could commit succesfully." >&2
  exit 1;
fi

echo "Commited changes."

echo "${PUSH}"

if [[ ! -z "${PUSH}" ]]
then
  ${PUSH}
  if [[ "${?}" -ne 0 ]]
  then 
    echo "Could not push changes to remote branch";
    exit 1;
  fi
  
  echo "Pushed changes to remote branch."
fi

exit 0;
